export const githubDarkTheme = {
  'code[class*="language-"]': {
    color: "#c9d1d9",
    background: "none",
    fontFamily:
      'ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, "Liberation Mono", monospace',
    textAlign: "left",
    whiteSpace: "pre",
    wordSpacing: "normal",
    wordBreak: "normal",
    wordWrap: "normal",
    lineHeight: "1.5",
    tabSize: "4",
    hyphens: "none",
  },
  'pre[class*="language-"]': {
    color: "#c9d1d9",
    background: "#0d1117",
    padding: "1.5em",
    margin: "0.5em 0",
    overflow: "auto",
    borderRadius: "12px",
    border: "1px solid #30363d",
  },
  comment: { color: "#8b949e", fontStyle: "italic" },
  prolog: { color: "#8b949e" },
  doctype: { color: "#8b949e" },
  cdata: { color: "#8b949e" },
  punctuation: { color: "#c9d1d9" },
  namespace: { opacity: ".7" },
  property: { color: "#79c0ff" },
  tag: { color: "#7ee787" },
  boolean: { color: "#ff7b72" },
  number: { color: "#ff7b72" },
  constant: { color: "#79c0ff" },
  symbol: { color: "#79c0ff" },
  deleted: { color: "#ffa198", backgroundColor: "#490202" },
  selector: { color: "#7ee787" },
  "attr-name": { color: "#79c0ff" },
  string: { color: "#a5d6ff" },
  char: { color: "#a5d6ff" },
  builtin: { color: "#79c0ff" },
  inserted: { color: "#7ee787", backgroundColor: "#04260f" },
  operator: { color: "#ff7b72" },
  entity: { color: "#79c0ff", cursor: "help" },
  url: { color: "#79c0ff" },
  ".language-css .token.string": { color: "#79c0ff" },
  ".style .token.string": { color: "#79c0ff" },
  variable: { color: "#ffa657" },
  atrule: { color: "#ff7b72" },
  "attr-value": { color: "#a5d6ff" },
  function: { color: "#d2a8ff" },
  keyword: { color: "#ff7b72" },
  regex: { color: "#a5d6ff" },
  important: { color: "#ff7b72", fontWeight: "bold" },
  bold: { fontWeight: "bold" },
  italic: { fontStyle: "italic" },
};
